In [20]:
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\My Pc\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\My Pc\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
import openpyxl

In [13]:
df=pd.read_csv('car_dataset_40x20.csv')
print(df.head())

  Car_ID     Brand   Model  Year Fuel_Type Transmission  Engine_CC  \
0   C001  Mahindra  XUV300  2015       CNG       Manual       1199
1   C002    Maruti  Brezza  2021    Petrol       Manual       1248
2   C003  Mahindra    Thar  2018    Petrol       Manual        998
3   C004     Honda   Amaze  2018    Hybrid       Manual       1197
4   C005     Honda    City  2022    Diesel    Automatic       1499

   Mileage_kmpl  Price_Lakh  Owner_Count  Kilometers_Driven   Color Body_Type  \
0          21.9       11.94            2             145442  Silver       SUV
1          18.8        7.96            1              66097  Silver       SUV
2          22.2       11.39            1             111848   Black       SUV
3          17.1       10.21            1              82848   Black     Sedan
4          13.1       12.00            1              37049   Brown     Sedan

   Seating_Capacity        City       Seller_Type Insurance_Valid  \
0                 5   Hyderabad  Certified Dealer             Yes
1                 5  Vijayawada  Certified Dealer             Yes
2                 4  Vijayawada        Individual              No
3                 5   Hyderabad        Individual              No
4                 5  Vijayawada  Certified Dealer              No

  Accident_History  Service_Cost_Rs  Resale_Value_Lakh
0               No             8168               2.78
1               No             6280               4.20
2               No             8007               4.10
3            Minor             7750               3.67
4               No            13349               7.20

In [ ]:
df.shape

(40, 20)

In [ ]:

df.columns

Index(['Car_ID', 'Brand', 'Model', 'Year', 'Fuel_Type', 'Transmission',
       'Engine_CC', 'Mileage_kmpl', 'Price_Lakh', 'Owner_Count',
       'Kilometers_Driven', 'Color', 'Body_Type', 'Seating_Capacity', 'City',
       'Seller_Type', 'Insurance_Valid', 'Accident_History', 'Service_Cost_Rs',
       'Resale_Value_Lakh'],
      dtype='str')

# writing dat into csv

In [5]:
import pandas as pd
Student_data={
    "Roll_no":[10,11,12,13],
    "name":["Aravind","Syam","Dhanush","Greesh"],
    "Dept":["CSE","IT","ECE","CSE"],
}
df=pd.DataFrame(Student_data)
df

   Roll_no     name Dept
0       10  Aravind  CSE
1       11     Syam   IT
2       12  Dhanush  ECE
3       13   Greesh  CSE

In [6]:
df.to_csv("Student_output.txt")
print("Succes")

Succes

In [7]:
df

   Roll_no     name Dept
0       10  Aravind  CSE
1       11     Syam   IT
2       12  Dhanush  ECE
3       13   Greesh  CSE

In [8]:
nf=pd.read_csv("Student_output.txt")
nf

   Unnamed: 0  Roll_no     name Dept
0           0       10  Aravind  CSE
1           1       11     Syam   IT
2           2       12  Dhanush  ECE
3           3       13   Greesh  CSE

In [9]:
df.columns

Index(['Roll_no', 'name', 'Dept'], dtype='str')

# JSON

In [ ]:
import pandas as pd
Student_data={
    "Roll_no":[10,11,12,13],
    "name":["Aravind","Syam","Dhanush","Greesh"],
    "Dept":["CSE","IT","ECE","CSE"],
}
df=pd.DataFrame(Student_data)
df.to_json("Students.json",orient='records',indent=4)
print("JSon file created")
df=pd.read_json('Students.json')
print("Student Data")
df

JSon file created
Student Data

   Roll_no     name Dept
0       10  Aravind  CSE
1       11     Syam   IT
2       12  Dhanush  ECE
3       13   Greesh  CSE

# Excel

In [4]:
Student_data={
    "Roll_no":[10,11,12,13],
    "name":["Aravind","Syam","Dhanush","Greesh"],
    "Dept":["CSE","IT","ECE","CSE"],
}
df=pd.DataFrame(Student_data)
df.to_excel("Student.xlsx",sheet_name="Student details",index=False)
print("Data written succesfully in excel")
df=pd.read_excel("Student.xlsx",sheet_name="Student details")
print("Data from excel file")
df

Data written succesfully in excel
Data from excel file

   Roll_no     name Dept
0       10  Aravind  CSE
1       11     Syam   IT
2       12  Dhanush  ECE
3       13   Greesh  CSE